# Generated by Django 6.0.3 on 2026-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên dịch vụ')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50, verbose_name='Icon')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Hình ảnh')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['order'],
            },
        ),
    ]
