# Generated by Django 6.0.3 on 2026-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='Hình ảnh')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thư viện ảnh',
                'verbose_name_plural': 'Thư viện ảnh',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
